feat: Introduce compose logs subcommand
unikraft/kraftkit pull request #1379
Opened 2024-03-06 12:54 UTC by LucaSeri

### Prerequisite checklist

  - [ ] Read the [contribution guidelines](https://unikraft.org/docs/contributing/) regarding submitting new changes to the project;
  - [ ] Tested your changes against relevant architectures and platforms;
  - [ ] Ran `make fmt` on your commit series before opening this PR;
  - [ ] Updated relevant documentation.

### Description of changes

* Allow users to start a project in detached mode ``kraft compose up -d``
* Handle prefixing logs when not following
* Introduce the ``kraft compose logs`` subcommand that allows users to print existing logs or follow them.

E.g:

```bash
kraft compose up -d

kraft compose logs --follow

ping-pong-pong  | Received: ping
ping-pong-ping  | Received: pong
ping-pong-pong  | Received: ping
```

2024-03-07 09:07 UTC, craciunoiuc commented on internal/cli/kraft/compose/logs/logs.go
> +	var wg sync.WaitGroup
shouldn't this be private? Is it used anywhere else?

`printLogs`

2024-03-07 09:08 UTC, craciunoiuc commented on internal/cli/kraft/compose/logs/logs.go
> +	for i := range project.Services {
wouldn't it look better to just do:

`for _, service := range project.Services {`

and then

`(service)`

?

2024-03-07 09:09 UTC, craciunoiuc commented on internal/cli/kraft/compose/logs/logs.go
> +	for i := range project.Services {
Actually even better, only the name seems to be used, so

`(service.Name)` and then use a `name` variable inside everywhere

2024-03-07 09:10 UTC, craciunoiuc commented on internal/cli/kraft/compose/logs/logs.go
> +	var wg sync.WaitGroup
Nvm, saw it used  in some other place also below.

Move it please to a `internal/cli/kraft/compose/utils/utils.go` file and make public there

2024-03-07 09:10 UTC, craciunoiuc requested changes
left you some comments inline, overall looks fine

2024-03-14 09:29 UTC, LucaSeri commented
Thanks @craciunoiuc for the comments. Part of this PR was actually migrated to https://github.com/unikraft/kraftkit/pull/1402, and ``kraft compose logs`` is now almost trivial.

2024-03-14 09:52 UTC, nderjung approved these changes
Thanks!

2024-03-14 10:01 UTC, craciunoiuc approved these changes
All good here. Thanks!

Reviewed-by: Cezar Craciunoiu <cezar.craciunoiu@unikraft.io>

2024-03-14 10:04 UTC, merged