feat: Introduce kraftfile-runtime builder
unikraft/kraftkit pull request #1386
Opened 2024-03-08 14:40 UTC by nderjung

This PR introduces a new build context (builder) to the `kraft build` subcommand which recognizes contexts where a `Kraftfile` has a `runtime` element.

In some cases, the user may still wish to use this command (often out of habit) and expect an action to have occurred.  It is possible in this circumstance to build the rootfs which is traditional considered a build step.  Whilst the rootfs may still be constructed at package-time, this introduction offers a convenient mechanism for performing the same action.

2024-03-12 10:08 UTC, craciunoiuc requested changes
Hey @nderjung 

Looks okay, some code to test this would be nice

2024-03-12 10:08 UTC, craciunoiuc commented on internal/cli/kraft/build/builder_kraftfile_runtime.go
> +	// return runtime.Unpack(ctx, opts.Workdir)
Some forgotten code

2024-03-13 08:05 UTC, nderjung commented
Rebased removing the lingering comments, but did not include any new tests.

2024-03-13 10:19 UTC, craciunoiuc commented on internal/cli/kraft/build/builder_kraftfile_runtime.go
> +	return fmt.Errorf("cannot calculate statics of pre-built unikernel runtime")
```suggestion
	return fmt.Errorf("cannot calculate statistics of pre-built unikernel runtime")
```

2024-03-13 10:19 UTC, craciunoiuc approved these changes
All good here. Thanks!

Reviewed-by: Cezar Craciunoiu <cezar.craciunoiu@unikraft.io>
Approved-by: Cezar Craciunoiu <cezar.craciunoiu@unikraft.io>

2024-03-13 10:23 UTC, merged