.github: Add PR and Issue templating
unikraft/kraftkit pull request #159
Opened 2022-11-28 14:26 UTC by craciunoiuc

The template is imported and modified from the main unikraft repository.

2022-12-21 20:05 UTC, nderjung requested changes
All good, just address the few inline issues + the codacy issue with the whitespace before the `-` in markdown lists

2022-12-21 20:05 UTC, nderjung commented on .github/PULL_REQUEST_TEMPLATE.md
> + - [ ] Ran `go fmt` on your commit series before opening this PR;
`make fmt`

2022-12-21 20:05 UTC, nderjung commented on .github/PULL_REQUEST_TEMPLATE.md
> + - Architecture(s): [e.g. `x86_64`, `arm`, `arm64`, or N/A]
Can delete

2022-12-21 20:05 UTC, nderjung commented on .github/PULL_REQUEST_TEMPLATE.md
> + - Operating System(s): [e.g. `windows`, `linux`, `macOS`, or N/A]
Not yet relevant, can remove

2022-12-21 20:05 UTC, nderjung commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +        * [Unikraft Discussions Forum](https://github.com/unikraft/kraftkit/discussions)
We don't have a discussions forum for kraftkit, so we can switch it back to the unikraft core repo for discussions

2022-12-21 20:05 UTC, nderjung commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +        - macOS
let's be more specific here and only add the platform's we're currently supporting:
```
- linux/debian
- linux/fedora
- linux/alpine
```

2022-12-21 20:05 UTC, nderjung commented on .github/ISSUE_TEMPLATE/config.yml
> +    url: https://github.com/unikraft/kraftkit/discussions/new
Switch to unikraft core repo discussions forum

2022-12-21 20:05 UTC, nderjung commented on .github/ISSUE_TEMPLATE/project_backlog.yml
> +  - type: textarea
Same here re:discussions forum

2022-12-21 20:05 UTC, nderjung commented on .github/ISSUE_TEMPLATE/project_backlog.yml
> +        - macOS
same again with os disbutions

2022-12-21 20:05 UTC, nderjung commented on .github/ISSUE_TEMPLATE/project_backlog.yml
> +        - macOS
maybe also we can add "other"

2023-01-14 09:21 UTC, craciunoiuc commented
I suggest we just ignore the files inside the templating, it seems I can't please Codacy here

<https://docs.codacy.com/repositories-configure/ignoring-files/>

2023-01-14 16:09 UTC, nderjung commented
> I suggest we just ignore the files inside the templating, it seems I can't please Codacy here
> 
> https://docs.codacy.com/repositories-configure/ignoring-files/

I agree.

2023-01-19 10:04 UTC, nderjung approved these changes
Looks good, thanks!

2023-01-19 10:05 UTC, merged