fix(refactor): Deprecate `unikraft.TypeNameVersion` in favour of `fmt.Stringer` implemented by `Nameable` interface
unikraft/kraftkit pull request #333
Opened 2023-04-09 01:35 UTC by afzal442

Closes: #268 

### Prerequisite checklist

  - [ ] Read the [contribution guidelines](https://unikraft.org/docs/contributing/) regarding submitting new changes to the project;
  - [ ] Tested your changes against relevant architectures and platforms;
  - [ ] Ran `make fmt` on your commit series before opening this PR;
  - [ ] Updated relevant documentation.

### Description of changes

2023-04-13 14:49 UTC, afzal442 commented
Hi there, I hv been struggling wid some errs and can u take a look here? Do I have to create `struct` here? Thanks

```
Error: unikraft/type.go:114:7: invalid receiver type Nameable (pointer or interface type)
Error: unikraft/type.go:116:12: entity.Type undefined (type *Nameable is pointer to interface, not interface)
```

cc @nderjung

2023-04-15 08:14 UTC, nderjung commented
Hi @afzal442, thanks for having a look at this! Interfaces in Go cannot be instantiated in the same way as structures and as such implementing the `String()` method on the interface directly will result in a compile-time error.  Instead, each structure which implements the interface must include the `String` method. 

My suggestion is to implement `String()` on all implementing components which in fact return the `unikraft.TypeNamVersion` such that their output is standardized, e.g. for the unikraft component:

```go
func (uc UnikraftConfig) String() string {
  return unikraft.TypeNameVersion(uc)
}
```

2023-04-17 20:28 UTC, afzal442 commented
Got tha idea. Thanks much! I have to implement String() on all implementing components `UnikraftConfig`.

2023-04-17 20:29 UTC, afzal442 commented on cmd/kraft/build/build.go
> +				project.Template().String(),
Should I revert all of it?

2023-04-17 20:30 UTC, afzal442 commented on unikraft/type.go
> +func (entity MyNm) String() string {
Here too!

2023-04-24 06:08 UTC, nderjung commented on unikraft/type.go
>  // <TYPE>/<NAME>:<VERSION>
```diff

- // TypeNameVersion returns the canonical name of the component using the format
- // String() returns the canonical name of the component using the format
- // <TYPE>/<NAME>:<VERSION>
+ // String implements fmt.Stringer and returns the canonical string
+ // representation of the nameable object
```

2023-04-24 06:08 UTC, nderjung commented on cmd/kraft/build/build.go
> +				project.Template().String(),
No, keep as is

2023-04-24 06:08 UTC, nderjung commented on unikraft/type.go
> +func (entity MyNm) String() string {
No, [as per my previous comment](https://github.com/unikraft/kraftkit/pull/333#issuecomment-1509627769), please implement `String()` in each component and not in the interface.

2023-04-24 16:29 UTC, nderjung requested changes
Hi @afzal442 looks like you need to rebase to staging as it's including already committed code (in particular code from [this commit](https://github.com/unikraft/kraftkit/commit/5dbd551189e00aac8597cb2fb51a21f6032157d6) and [this commit](https://github.com/unikraft/kraftkit/commit/2bb730a0a7a300f2d4e570ef71d0595f4bb312b8)) which is resulting in merge conflicts (and so therefore the GitHub actions workflow cannot be run).

Please also correct the spelling mistakes in your commit message.

2023-04-29 18:10 UTC, nderjung commented
Hi @afzal442, please can you view and address the checks that are failing? Additionally, rebasing to `staging` will invoke more up-to-date checks. Thanks!

2023-04-29 20:10 UTC, afzal442 commented
Sorry @nderjung ! I am done. Could you review it? Thanks

2023-04-29 21:22 UTC, nderjung commented on unikraft/type.go
> +func TypeNameVersion(entity fmt.Stringer) string {
You can discard this change.

2023-04-29 21:24 UTC, nderjung commented
Please see my inline comment which requests to discard the highlighted change. Additionally, please squash your commits into a single commit which has a commit title the same as this PR. :)

2023-04-30 06:20 UTC, afzal442 commented
> Please see my inline comment which requests to discard the highlighted change

Hi @nderjung I had already pointed out [this](https://github.com/unikraft/kraftkit/pull/333#discussion_r1169237652) in fact. But you said no. That's why there was no point of deprecation of `unikraft.TypeNameVersion`. LMK if I understood here.

2023-04-30 06:21 UTC, afzal442 commented on unikraft/type.go
> +func TypeNameVersion(entity fmt.Stringer) string {
Yep! on it.

2023-10-19 13:22 UTC, closed without merging