docs(readme): add latest release badge
unikraft/kraftkit pull request #340
Opened 2023-04-11 09:52 UTC by R3DRUN3

- [X] Read the [contribution guidelines](https://unikraft.org/docs/contributing/) regarding submitting new changes to the project;
  - [X] Updated relevant documentation.

### Description of changes
*SAFE TO MERGE PR*
Added latest release badge to readme:
![GitHub release (latest SemVer)](https://img.shields.io/github/v/release/unikraft/kraftkit)

2023-04-12 17:03 UTC, nderjung requested changes
Hi @R3DRUN3! Thanks for the contribution! This is a great idea. Just one-inline suggestion and need you to force-push with a sign-off (`git commit -s`) before we can merge.

2023-04-12 17:03 UTC, nderjung commented on README.md
> +![GitHub release (latest SemVer)](https://img.shields.io/github/v/release/unikraft/kraftkit)
```diff
- ![GitHub release (latest SemVer)](https://img.shields.io/github/v/release/unikraft/kraftkit)
+ ![Latest release](https://img.shields.io/github/v/release/unikraft/kraftkit)
```

2023-04-13 07:12 UTC, R3DRUN3 commented
> Hi @R3DRUN3! Thanks for the contribution! This is a great idea. Just one inline suggestion and need you to force-push with a sign-off (`git commit -s`) before we can merge.

Hi @nderjung, done! 👍

2023-04-13 07:13 UTC, R3DRUN3 commented on README.md
> +![GitHub release (latest SemVer)](https://img.shields.io/github/v/release/unikraft/kraftkit)
Hi @nderjung, done! 👍

2023-04-13 07:13 UTC, R3DRUN3 commented
> Hi @R3DRUN3! Thanks for the contribution! This is a great idea. Just one inline suggestion and need you to force-push with a sign-off (`git commit -s`) before we can merge.

Hi @nderjung, done! 👍

2023-04-13 07:47 UTC, nderjung requested changes
Hi @R3DRUN3, please squash both commits together; simply 1 commit together and then force push. The workflow should be:

```
git stash;
git rebase -i HEAD~2;
```
Now, in the editor:
```diff
- pick a7aaac7 docs(readme): add latest release badge
- pick 1c0fd6f docs(readme): @nderjung inline suggestion
+ r a7aaac7 docs(readme): add latest release badge
+ f 1c0fd6f docs(readme): @nderjung inline suggestion
```

Then edit the message to be:
```
doc(readme): add latest release badge

Signed-off-by: ...
```

Add your name and email at `...` in the format `Name <email@com>`

Once the editor closes, force push to the branch:
```
git stash pop;
git push -u --force origin staging
```

2023-04-13 08:03 UTC, R3DRUN3 commented
@nderjung  ok, now it should be good 😊

2023-04-13 09:15 UTC, nderjung commented
Hi, just one thing, it's `doc` instead of `docs`! :)

2023-04-13 09:17 UTC, merged