feat: Add basic login method
unikraft/kraftkit pull request #390
Opened 2023-04-18 11:13 UTC by nderjung

### Prerequisite checklist

  - [x] Read the [contribution guidelines](https://unikraft.org/docs/contributing/) regarding submitting new changes to the project;
  - [x] Tested your changes against relevant architectures and platforms;
  - [x] Ran `make fmt` on your commit series before opening this PR;
  - [ ] Updated relevant documentation.

### Description of changes

This PR introduces a new subcommand `kraft login` which manipulates KraftKit's configuration file such that it populates the list of authenticated services.

2023-04-19 12:29 UTC, craciunoiuc requested changes
Hey @nderjung 

I tried to use this to `pull` a private repository.

Not sure if I did something wrong but It did not work. The values are set correctly in the config, but are not used by the pulling mechanism

2023-04-19 12:29 UTC, craciunoiuc commented on cmd/kraft/login/login.go
> +		return fmt.Errorf("must speficy at least `--user` or `--token`")
```suggestion
		return fmt.Errorf("must specify at least `--user` or `--token`")
```

2023-04-19 12:29 UTC, craciunoiuc commented on cmd/kraft/login/login.go
> +	if opts.User == "" && opts.Token == "" {
This only works if the provided argument `--token` is `""`. If left empty it will just assume that the password/token is the next argument.

2023-04-19 12:29 UTC, craciunoiuc commented on cmd/kraft/login/login.go
> +	if opts.User == "" && opts.Token == "" {
Also setting through env variables does not currently work it seems

The username is caught correctly, but the token is not

2023-04-20 11:51 UTC, nderjung commented
Hi @craciunoiuc, thanks for the feedback.  The fact that Git cannot be authenticated is a separate issue to this.  This is simply adding an auth entry to the configuration file.

2023-04-20 11:52 UTC, nderjung commented on cmd/kraft/login/login.go
> +		return fmt.Errorf("must speficy at least `--user` or `--token`")
Good catch, thanks!

2023-04-20 11:52 UTC, nderjung commented on cmd/kraft/login/login.go
> +	if opts.User == "" && opts.Token == "" {
The goal here is to XOR `User` and `Token`.  Env var should work, can you double check? It's definitely set in the structure tag

2023-04-20 15:33 UTC, nderjung commented on cmd/kraft/login/login.go
> +	if opts.User == "" && opts.Token == "" {
The two usages are
```
kraft -t TOKEN domain.com
```
and
```
kraft -u USER -p PASS domain.com
```

2023-04-21 09:05 UTC, craciunoiuc approved these changes
All good here. Thanks!

Reviewed-by: Cezar Craciunoiu <cezar.craciunoiu@unikraft.io>
Approved-by: Cezar Craciunoiu <cezar.craciunoiu@unikraft.io>

2023-04-21 09:07 UTC, merged