feat(errorTracing): add error tracing
unikraft/kraftkit pull request #479
Opened 2023-05-16 01:41 UTC by zyllee

### Prerequisite checklist

  - [x] Read the [contribution guidelines](https://unikraft.org/docs/contributing/) regarding submitting new changes to the project;
  - [x] Tested your changes against relevant architectures and platforms;
  - [ ] Ran `make fmt` on your commit series before opening this PR;
  - [ ] Updated relevant documentation.

### Description of changes

To add the feature related to #34.
The [juju](https://github.com/juju/errors) package for error handling is currently imported. Wrote the test code.

2023-05-16 07:19 UTC, nderjung requested changes
Hi @zyllee, thanks for this contribution!

The issue you've addressed is out-of-date in terms of its implementation but not its requirements. We have since added [`internal/errs`](https://github.com/unikraft/kraftkit/tree/staging/internal/errs) to KraftKit which now stores error types (instead of `iota`/`int`s, they're `string`s).

As discussed on Discord, the need for a error tracing system is still required and [juju's errors module](https://github.com/juju/errors) still seems like a good fit.

Based on the juju errors' README, you would technically need to use the juju `errors` package to replace the internal package's definition of `errors` with juju's, i.e.:
```diff
index 8206a12..4d88304 100644
--- a/internal/errs/defs.go
+++ b/internal/errs/defs.go
@@ -4,7 +4,9 @@
 // You may not use this file expect in compliance with the License.
 package errs

-import "errors"
+import
+       "github.com/juju/errors"
+)
```

**However,** we actually do NOT need to replace the above, in fact, since `internal/errs` declares the same (subset) of `errors`, this can be removed since they will be duplicate. Only when we add new error types (which is possible), would we need to restore this package with custom definitions. Let's hold off for now and simply remove this package.

Instead, to continue this work, I would recommend going through the KraftKit source code and replacing all instances of `return fmt.Errorf` and `errors.New` with valid juju `errors` wrappers. This will allow us to a). classify each error into a category and b). allow us to unwrap each error nicely since the system will homogenise. The moment where errors are actually printed to the console occurs in [`cmdfactory.Main`](https://github.com/unikraft/kraftkit/blob/staging/cmdfactory/builder.go#L181):

https://github.com/unikraft/kraftkit/blob/06bef518ea77d6ff8d80db3c25bf1064d3e4d7ee/cmdfactory/builder.go#L175-L184

Replace `fmt.Printf(err)` with `errors.ErrorStack(err)`

For the first iteration on your side, this needs to be replace with juju errors' [`Unwrap`](https://pkg.go.dev/github.com/juju/errors#Unwrap) or [`Trace`](https://pkg.go.dev/github.com/juju/errors#Trace) method which will output the call stack or the list of errors which have occurred.



Finally, the code related to "user" look up can be removed entirely since this is out-of-scope of the project.

2023-05-25 14:33 UTC, zyllee commented on cmd/kraft/build/build.go
> +		return errors.Errorf("the `--arch` and `--plat` options are not supported in addition to `--target`")
![image-20230525211724259](https://github.com/unikraft/kraftkit/assets/16526254/c255f8a8-b337-4ed4-9927-333ae342039a)

2023-05-25 14:33 UTC, zyllee commented on cmd/kraft/build/build.go
> +		return errors.Errorf("cannot build uninitialized project! start with: ukbuild init")
![image-20230525214438050](https://github.com/unikraft/kraftkit/assets/16526254/4268ba92-4239-4a74-9da1-d71dddc4646b)

2023-05-25 14:34 UTC, zyllee commented on cmd/kraft/build/build.go
> +			return errors.Errorf("could not complete search: %v", err)
![image-20230525221207184](https://github.com/unikraft/kraftkit/assets/16526254/c15a1a21-1e01-48c3-bf5f-fc1d477776be)

2023-05-25 14:35 UTC, zyllee commented on cmd/kraft/build/build.go
> +			return errors.Errorf("could not pull all components: %v", err)
![image-20230525220202351](https://github.com/unikraft/kraftkit/assets/16526254/421bd6d8-be4f-4dca-8138-f41c1f43f159)

2023-05-25 14:35 UTC, zyllee commented on cmd/kraft/build/build.go
> +		return errors.Errorf("no targets selected to build")
![image-20230525220353280](https://github.com/unikraft/kraftkit/assets/16526254/9b93381c-ea9f-4349-9d08-33e432272f41)

2023-05-25 14:45 UTC, zyllee commented
The screenshots above are running in cmd `kraft build --arch x86_64 --plat kvm`. I test it by changing `if` condition to satisfied return error to happen.

2023-06-14 07:55 UTC, zyllee commented on archive/archive.go
> +		return errors.Annotatef(err, "tar:%v", err)
juju's error package can't handle %w format. So I try to implement in this way to have same effect.

2024-01-08 16:01 UTC, nderjung commented
Closing due to age and it requiring a large rebase.

2024-01-08 16:01 UTC, closed without merging