refactor!: Adjust package managers for external use
unikraft/kraftkit pull request #498
Opened 2023-05-29 18:22 UTC by nderjung

### Prerequisite checklist

  - [x] Read the [contribution guidelines](https://unikraft.org/docs/contributing/) regarding submitting new changes to the project;
  - [x] Tested your changes against relevant architectures and platforms;
  - [x] Ran `make fmt` on your commit series before opening this PR;
  - [ ] Updated relevant documentation.

### Description of changes

This PR series adjusts the use of the embedded kraftkit package managers for external use as Go packages. No functional changes occur, only API changes.

2023-05-30 09:48 UTC, craciunoiuc commented on packmanager/manager.go
> +type NewManagerConstructor func(context.Context, ...any) (PackageManager, error)
scary :sweat_smile:

2023-05-30 09:53 UTC, craciunoiuc requested changes
![image](https://github.com/unikraft/kraftkit/assets/46280801/c2c15f00-73bc-4b07-8a25-1f000814e630)


I suppose we'll never know `and` what

2023-05-30 12:21 UTC, antoineco commented
> and, adds the ability [...]
:)

2023-06-02 06:39 UTC, nderjung commented
@craciunoiuc this is good to go, can you have another look?

2023-06-02 07:32 UTC, craciunoiuc approved these changes
All good here. Thanks!

Reviewed-by: Cezar Craciunoiu <cezar.craciunoiu@unikraft.io>
Approved-by: Cezar Craciunoiu <cezar.craciunoiu@unikraft.io>

2023-06-02 07:33 UTC, merged