Add `kraftld`
unikraft/kraftkit pull request #703
Opened 2023-08-03 09:18 UTC by mkroening

### Prerequisite checklist

  - [x] Read the [contribution guidelines](https://unikraft.org/docs/contributing/) regarding submitting new changes to the project;
  - [x] Tested your changes against relevant architectures and platforms;
  - [ ] Ran `make fmt` on your commit series before opening this PR;
  - [ ] Updated relevant documentation.

### Description of changes

This implements a `kraftld` linker shim acting as a gcc-style linker.

It accepts the same arguments and forwards them to `UK_LDFLAGS`. It removes flags that are known to be incompatible. Furthermore, it sanitizes relative paths for the Unikraft build system.

`kraftld` also extracts any file dependencies for `UK_LDEPS`. Lastly, it parses `-o <OUTPUT>` and copies the KraftKit output image correspondingly. Currently, it assumes the `default_qemu-x86_64`.
Future versions of KraftKit will support an output option, which `kraftld` will then migrate to.

`kraftld` is currently targeting the Rust compiler. Other compilers may or may not work as well.

2023-08-03 09:21 UTC, mkroening commented
This script is currently not capable of handling paths with white spaces. They could be escaped, but KraftKit does not seem to work with white spaces in paths anyway.

2023-10-02 12:20 UTC, craciunoiuc requested changes
Hey @mkroening

I am now looking over this and I left you some comments. Most are optional, but I would recommend you try to go around and implement them

2023-10-02 12:20 UTC, craciunoiuc commented on scripts/kraftld
> +#!/usr/bin/env bash
Would it be possible to go over it and switch from `bash` to `sh` to make sure it works everywhere? 🙏 

By switching I get the following errors:
```
shellcheck scripts/kraftld

In scripts/kraftld line 4:
set -euo pipefail
         ^------^ SC3040 (warning): In POSIX sh, set option pipefail is undefined.


In scripts/kraftld line 5:
IFS=$'\n\t'
    ^-----^ SC3003 (warning): In POSIX sh, $'..' is undefined.


In scripts/kraftld line 17:
LDFLAGS=${LDFLAGS/-nodefaultlibs/}
        ^------------------------^ SC3060 (warning): In POSIX sh, string replacement is undefined.


In scripts/kraftld line 24:
while [[ $# -gt 0 ]]; do
      ^------------^ SC3010 (warning): In POSIX sh, [[ ]] is undefined.


In scripts/kraftld line 44:
            FILES+=" $1"
            ^---^ SC3024 (warning): In POSIX sh, += is undefined.

For more information:
  https://www.shellcheck.net/wiki/SC3003 -- In POSIX sh, $'..' is undefined.
  https://www.shellcheck.net/wiki/SC3010 -- In POSIX sh, [[ ]] is undefined.
  https://www.shellcheck.net/wiki/SC3024 -- In POSIX sh, += is undefined.
```

2023-10-02 12:20 UTC, craciunoiuc commented on scripts/kraftld
> +#!/usr/bin/env bash
It's not mandatory to do right now

2023-10-02 12:20 UTC, craciunoiuc commented on scripts/kraftld
> +kraft build
```suggestion
kraft build --no-cache $KRAFTKIT_ARG_TARG $KRAFTKIT_ARG_PLAT $KRAFTKIT_ARG_ARCH
```

2023-10-02 12:20 UTC, craciunoiuc commented on scripts/kraftld
> +            ;;
```suggestion
        -L)
            # Ignore other options with arguments
            shift
            shift
            ;;
        -t)
            # Set the kraftkit build target
            KRAFTKIT_TARG="$2"
            shift
            shift
            ;;
        -a)
            # Optionally set kraftkit build arch
            KRAFTKIT_ARCH="$2"
            shift
            shift
            ;;
        -p)
            # Optionally set kraftkit build plat
            KRAFTKIT_PLAT="$2"
            shift
            shift
            ;;
```

2023-10-02 12:20 UTC, craciunoiuc commented on scripts/kraftld
> +            ;;
This assumes that a name is provided. You can create `kraft.yaml` files without, but it's fine

2023-10-02 12:20 UTC, craciunoiuc commented on scripts/kraftld
> +cp .unikraft/build/default_qemu-x86_64 "$OUTPUT"
```suggestion
cp .unikraft/build/${KRAFTKIT_TARG}_${KRAFTKIT_PLAT}-${KRAFTKIT_ARCH} "$OUTPUT"
```

2023-10-02 12:20 UTC, craciunoiuc commented on scripts/kraftld
> +cp .unikraft/build/default_qemu-x86_64 "$OUTPUT"
If the target matches multiple files, it means that probably it's wrong anyways. We could parse the `kraft.yaml` with `yq` but it might get a bit too complicated.

2023-10-02 12:20 UTC, craciunoiuc commented on scripts/kraftld
> +
```suggestion
if -n "$KRAFTKIT_TARG"; then
  echo "A target needs to be provided"
  exit 1
else
  KRAFTKIT_ARG_TARG="-t $KRAFTKIT_TARG"
fi
if -n "$KRAFTKIT_ARCH"; then
  KRAFTKIT_ARCH="*"
  KRAFTKIT_ARG_ARCH=""
else
  KRAFTKIT_ARG_ARCH="-m $KRAFTKIT_ARCH"
fi
if -n "$KRAFTKIT_PLAT"; then
  KRAFTKIT_PLAT="*"
  KRAFTKIT_ARG_PLAT=""
else
  KRAFTKIT_ARG_PLAT="-p $KRAFTKIT_PLAT"
fi
```

2023-10-02 12:20 UTC, craciunoiuc commented on scripts/kraftld
> +cp .unikraft/build/default_qemu-x86_64 "$OUTPUT"
If the PLAT or ARCH are empty, they will match with stars, which should work

2023-10-02 12:20 UTC, craciunoiuc commented on scripts/kraftld
> +kraft build
This will complain about argument splitting, but that is intended :D

2023-10-02 13:13 UTC, mkroening commented on scripts/kraftld
> +#!/usr/bin/env bash
I'll look into it.

What platforms do we need to support that do not have bash?

2023-10-02 13:16 UTC, mkroening commented on scripts/kraftld
> +            ;;
Those arguments are not supported by the (GNU linker)[https://sourceware.org/binutils/docs-2.37/ld/Options.html#Options] and don't make sense as part of this script. Passing via environment variables should be fine.

2023-10-02 13:35 UTC, craciunoiuc commented on scripts/kraftld
> +#!/usr/bin/env bash
I think `MacOS` also has `bash`, but you never know what people use 😅 

As I said, it's not mandatory

2023-10-02 13:36 UTC, craciunoiuc commented on scripts/kraftld
> +            ;;
Oh, didn't know this sits somewhere in the middle, yes, envvars it is then

2023-10-05 12:16 UTC, mkroening commented on scripts/kraftld
> +#!/usr/bin/env bash
All right. I'd rather not pass on the features of bash if there is no use case yet. 😅

2023-10-05 12:57 UTC, mkroening commented on scripts/kraftld
> +kraft build
Done, but with arrays for explicit argument splitting. 👍

2023-10-05 12:59 UTC, mkroening commented on scripts/kraftld
> +cp .unikraft/build/default_qemu-x86_64 "$OUTPUT"
That did not work, since this also matches all other files with extensions:

```
default_qemu-x86_64
default_qemu-x86_64.bootinfo
default_qemu-x86_64.bootinfo.cmd
default_qemu-x86_64.cmd
default_qemu-x86_64.dbg
default_qemu-x86_64.dbg.cmd
default_qemu-x86_64.dbg.gdb.py
default_qemu-x86_64.gz
default_qemu-x86_64.gz.cmd
```

Instead, I used `find`.

2023-10-05 12:59 UTC, mkroening commented on scripts/kraftld
> +
I adapted and incorporated this.

2023-10-05 13:00 UTC, mkroening commented
Thanks for the review! :)
I did a rework with all of your suggestions, apart from not using Bash, @craciunoiuc.

I added documentation and adapted the environment variables to also adapt an unnamed implicit configuration (`workspace`).

2023-10-21 15:18 UTC, craciunoiuc commented
@nderjung as you are a bit more 'diverse' this week, can you take a look/give an answer on this?

2023-12-05 15:15 UTC, craciunoiuc approved these changes
All good here. Thanks!

Reviewed-by: Cezar Craciunoiu <cezar.craciunoiu@unikraft.io>

2023-12-05 15:18 UTC, nderjung approved these changes
Thanks a lot @mkroening! Apologies this took so long to get in.

2023-12-05 15:18 UTC, merged

2023-12-05 19:40 UTC, mkroening commented
Thank you so much! :)