feat: Upgrade `Kraftfile` specification to v0.6
unikraft/kraftkit pull request #757
Opened 2023-08-29 12:50 UTC by nderjung

### Prerequisite checklist

  - [x] Read the [contribution guidelines](https://unikraft.org/docs/contributing/) regarding submitting new changes to the project;
  - [x] Tested your changes against relevant architectures and platforms;
  - [x] Ran `make fmt` on your commit series before opening this PR;
  - [ ] Updated relevant documentation.

### Description of changes

This PR introduces a new `Kraftfile` specification which makes new adjustments to the user's workflow such that it is easier to run applications in binary compatibility mode.

(WIP)

2023-08-29 18:20 UTC, craciunoiuc requested changes
Went through the whole PR

Feels like it needs to be split up into at least 2 PRs, maybe 3

1 with the fixes, 1 with the spec update and 1 with the initrd work

2023-08-29 18:20 UTC, craciunoiuc commented on unikraft/app/application.go
> +	Libraries(ctx context.Context) (map[string]*lib.LibraryConfig, error)
In the commit (commit 1) message for this change: `ambigiuity` -> `ambiguity`

2023-08-29 18:20 UTC, craciunoiuc commented on oci/image.go
> +func (image *Image) SetEntrypoint(_ context.Context, entrypoint string) {
In commit (`feat: Populate application entrypoint from Kraftfile`) message `packaginf` -> `packaging`

2023-08-29 18:20 UTC, craciunoiuc commented on action.yml
> +  rootfs:
In commit `feat!: Introduce dynamic initramfs serialization for root filesystems` `underelying` -> `underlying`

2023-08-29 18:20 UTC, craciunoiuc commented on initrd/dockerfile.go
> +// NewFromDockerfile accepts an input path which represents a Dockerfile that is
`is` -> ` `

2023-09-06 15:12 UTC, craciunoiuc commented on initrd/dockerfile.go
> +			return fmt.Errorf("could not writer CPIO header: %w", err)
`write`

2023-09-06 15:13 UTC, craciunoiuc commented on initrd/dockerfile.go
> +			Size:     info.Size(),
Are permissions in initramfs fixed now?

2023-09-08 11:30 UTC, nderjung commented on initrd/dockerfile.go
> +			Size:     info.Size(),
Maybe 🤷

2023-10-17 19:37 UTC, craciunoiuc commented on unikraft/target/transform.go
> +
Can cause sigsegv it's not tested

2023-10-17 20:00 UTC, craciunoiuc commented on oci/pack.go
> +			return nil, fmt.Errorf("could build layer from file: %w", err)
`not`

2023-10-19 10:09 UTC, craciunoiuc approved these changes
All good here. Thanks!

Reviewed-by: Cezar Craciunoiu <cezar.craciunoiu@unikraft.io>
Approved-by: Cezar Craciunoiu <cezar.craciunoiu@unikraft.io>

2023-10-19 10:09 UTC, merged