Fix makepkg for Archlinux
unikraft/kraftkit pull request #838
Opened 2023-09-24 23:52 UTC by SorenEricMent

### Prerequisite checklist

  - [ X ] Read the [contribution guidelines](https://unikraft.org/docs/contributing/) regarding submitting new changes to the project;
  - [ ] Tested your changes against relevant architectures and platforms;
  - [ ] Ran `make fmt` on your commit series before opening this PR;
  - [ ] Updated relevant documentation.

This change does not impact building, thus there is no need for funning make fmt nor updating relevant documentation. This patch is Arch Linux platform specific.

### Description of changes
Fixed makepkg command for ArchLinux, addressing issue https://github.com/unikraft/kraftkit/issues/837

Signed-off-by: Yunchuan "Winslow" Hu <i@winsloweric.com>

2023-09-25 07:47 UTC, craciunoiuc requested changes
Hey @SorenEricMent,

Thanks a lot for this fix. I left a comment for a change.

Also, can you change you commit message to have this format? Thanks
```
fix(webinstall): Correct use of `makepkg` for Arch Linux
```

2023-09-25 07:47 UTC, craciunoiuc commented on tools/webinstall/install.sh
> +        do_cmd "$MAKEPKG -si"
I would suggest returning to the previous directory after running the command, as we are deleting it anyways 1 line below.

```suggestion
        cd /tmp/kraftkit-bin
        do_cmd "$MAKEPKG -si"
        cd - 1> /dev/null
```
This works for me on `sh`, please confirm it also works for you

2023-09-27 08:28 UTC, craciunoiuc commented
Please also squash the 2 commits together and add the name above

2023-09-30 02:42 UTC, SorenEricMent commented
> Please also squash the 2 commits together and add the name above

Done!

2023-09-30 14:33 UTC, craciunoiuc commented
@SorenEricMent It's fine, no worries, but it seems you rebased one more commit and this PR now has two commits 😅 

Can you drop the second to last one and leave only yours? Thanks 🙏

2023-10-02 00:09 UTC, SorenEricMent commented
Should be good to go!

2023-10-02 07:28 UTC, craciunoiuc approved these changes
All good here. Thanks!

Reviewed-by: Cezar Craciunoiu <cezar.craciunoiu@unikraft.io>
Approved-by: Cezar Craciunoiu <cezar.craciunoiu@unikraft.io>

2023-10-02 07:30 UTC, merged