fix(pkg): Add `--force` flag to sourcing and prevent check on unsourcing
unikraft/kraftkit pull request #878
Opened 2023-10-13 11:08 UTC by nderjung

### Prerequisite checklist

  - [x] Read the [contribution guidelines](https://unikraft.org/docs/contributing/) regarding submitting new changes to the project;
  - [x] Tested your changes against relevant architectures and platforms;
  - [x] Ran `make fmt` on your commit series before opening this PR;
  - [ ] Updated relevant documentation.

### Description of changes

This commit fixes an issue whereby the user will have the compatibility of a source checked before the source is saved to config.  To prevent this check, a new `kraft pkg source --force` flag is added which prevents this check.

Inversely, when a source is being removed from `kraft pkg unsource`, its compatibility does not need to be checked because it is being removed, not only is this less computation but if the source was manually added by hand and it was invalid, it would be impossible to remove.

2023-10-13 11:13 UTC, craciunoiuc requested changes
Young Skywalker,

You forgot to add e2e tests to check this this new flag. Source/Unsource we test so no excuses :smiling_imp: 

Edit: The tests should run `--force` with a good entry, and a bad entry

2023-10-13 11:46 UTC, nderjung commented
You're right Sensai. I just created [a new PR](https://github.com/unikraft/kraftkit/pull/879) which helps me debug this because i was not sure where it was needed :) 

I'll rebase this once that PR is merged so that i can see where i need to add it.

2023-10-13 11:55 UTC, craciunoiuc commented
That PR has been vanquished

2023-10-13 13:50 UTC, nderjung commented
There's a bit of a catch-22 with adding new tests here. There are several fixes included in #873 which correctly handle non-compliant sources under the manifest manager. I'll open an issue to address adding test cases for the `--force` flag which are dependent on that PR being upstreamed.

2023-10-14 06:57 UTC, craciunoiuc approved these changes
All good here. Thanks!

Reviewed-by: Cezar Craciunoiu <cezar.craciunoiu@unikraft.io>
Approved-by: Cezar Craciunoiu <cezar.craciunoiu@unikraft.io>

2023-10-14 06:57 UTC, merged